name: shell commands

on: [push]

jobs:
  run-shell-command: 
    runs-on : ubuntu-latest 
    steps:  
      - name: echo a string 
        run: echo "Hello this is testing "
      - name: multiline script 
        run: | 
          node -v
          npm -v
      - name: Python Command
        run: |
          import platform 
          print(platform.processor())
        shell: python 

  run-windows-command:
    runs-on: windows
    steps: 
      - name: Directory Powershell
        run: Get-location
      - name: Directory on Bash
        run: pwd
        shell: bash